/*
 * SearchPanel.java
 *
 * Created on 10 de Dezembro de 2005, 17:18
 */

package org.neodatis.knowledger.gui.graph.panel;

import javax.swing.JFrame;

/**
 *
 * @author  olivier s
 */
public class SearchPanel extends javax.swing.JPanel {
    
    /** Creates new form SearchPanel */
    public SearchPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        tfKeyword = new javax.swing.JTextField();
        btSearchButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText(java.util.ResourceBundle.getBundle("knowledger.properties").getString("search"));

        tfKeyword.setName("tfKeyword");

        btSearchButton.setText(java.util.ResourceBundle.getBundle("knowledger.properties").getString("search"));
        btSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchButtonActionPerformed(evt);
            }
        });

        jButton2.setText("next");
        jButton2.setName("btSearchNext");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchNextActionPerformed(evt);
            }
        });
    }

        

    private void btSearchNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchNextActionPerformed
        System.out.println("next search of " + tfKeyword.getText());
    }

    private void btSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchButtonActionPerformed
        System.out.println("First search of " + tfKeyword.getText());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSearchButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfKeyword;
    // End of variables declaration//GEN-END:variables
    
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
    }
}
